[package]
name = "helloworld"
version = "0.1.0"
authors = ["Bruno Clemente"]
edition = "2018"

[dependencies]
libc = "0.2.0"
solder = { path = "../.." }

[lib]
name = "helloworld"
crate-type = ["dylib"]
